[gcp_service_account]
type = "service_account"
project_id = "feelings-455205"
private_key_id = "98a94f19497544335ddb4a282c922935319480b4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCur7hooo1fyReW
ZGVTWeHFKkgMpRi3LOwNAxULEV1Udfie8lr0ZGorMHMsrOCxWSY0eaTyr+Q4Np4i
Igqd+kg6dO+j5NJgVn1heMrbrQh70db8KcqI6fPlpgAM4yqzBLV7UQvbnzhfug8M
AzYf+ud35MTA4ga7jx2nc3qZ5yrWHSPFtfUPRjSPuHC9D9KwynDjKA3H2H1Taxfv
zPD5OM2CEs6qGGwHnH/IY3rp5R5DgKW1pATPE/ugdrptF2oq6hrFPJe8sDD6IUBC
d67NkHWOROZlhqbOFwb8dKtvCloly4jV81y/yHJqr9YNjWoLvQ6Qjfg5XVI8kidJ
IoUcF9I7AgMBAAECggEAMTOnMjmOrkr6jM6MR5TKZXlKP92Ef5t0hRm4JJzod7Ce
rU4/1hQuXynPVub+hpVAkIkur3hhRIAFvEFwUhy7mVN0Z+o8YwwZVonqQUOUXyO0
dOPkevnCS42c+ARH85JA95HVUC+hdjz2ngCNjyZhacCStm0zTkK6LH73KkAVLach
bcU7RmC2Io3m3aZdGge4MgjzX0Nzoa4FM9kd8v+qlmvBkLV39O3FsiLhru74ZwG+
wlyPZlRabeo6h/Mw9Bvvl8OYxWqqAkNncyVdqeuzPsxLQiAvVG6vzhiKctWgEH2r
9Dy+oETYc7hdomQz0C2hCOuk1Etlz6nkCwzAobH8SQKBgQDviawk3OgGGZ8sG2SX
RIZCzlV5Q182Up3DG6LaILjNNTItRvSDCZvdJQ2xfWs9veLgyoh2NncoZFWK1wdC
xYwZoOUmfY0F6rA75fRfYDxOZa3SGFfJZR+OoKjyZfB845qAcSRfgWl3Bgt6J4U4
DZYWWQ8X0nyiEmz5NOAbTy6/NQKBgQC6sRR2tVCuJUWrYEoLaxcI4BecvRLmqAUy
E3E5VdJfU5lVD+MChMt/AsxhJgPA9Rb/ZpM7dKCICSdLtYxyBMKgBkWZlxJsRXe7
wHPSWzYY80IM4EDN864PfMjJ+k1foqo86lNTNvj3+T8O2R9lAo5pjpg+46n5o7UZ
JvweLslJrwKBgGFUOkscK3bXEFL2qm/AWyFn/1jvZA+JkCrH3ursospW1BWLoCxi
Sh+YP7EfueRzdG1MPhhyVwZlhlCMwJmD9UIwmwuBtjxyOLuN2zapvrdIH1GfrIPb
f/APHbaobwf/3zZTQqk/xx+iqCUxS7MT6ikYdMaEMzoTbI3xyyGtkdwFAoGARJBm
aJZ8lAiCRsdtSjZBVnQel+TkvSt2BQcY7Sq0wWfNh2z3PWSR7AqWDxPMCyC4GoKM
jihuEKfz850wgGt5IxZKl3bhQDxfFeg/YUE4Y/9rAZmWk0zsXynAAFXZ9sah6Q9S
HNyyoTe7zfM10X4X2XKSPX6VXWafSyaDL36VVGcCgYAfdkyTyIUatZPSC0rCeOmX
I8VXbs4sQHLn2XYUjxmSagjic2O5xl1AAmGedcFPHgIdIBrti/2/R7rx0jqT4i9J
x9TIcEZQdlcyeowVY6Z0weSoRVgd6QS0kfeO4xsBzZ84NODDi4VYdZvKhsPEsPSq
yl1TnwmcDSD7Jnl/A/nGGQ==
-----END PRIVATE KEY-----"""
client_email = "feelings@feelings-455205.iam.gserviceaccount.com"
client_id = "113508851037320695594"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/feelings%40feelings-455205.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[names]
list = ["榊原凰成"]

[users]
list = ["大北", "河瀬", "林田", "橘", "竹内", "齋藤", "金田", "利守", "小﨑", "田中", "新開", "原野", "吉村"]
